spring:
  profiles:
    active: dev, third-party
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      poolName: HikariPoolZZZ
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082
  servlet:
    context-path: /api

swagger:
  version: "1.0"
  title: "Exchange Rate REST API"
  description: "Documentation for the Exchange Rate demo application."
  contact:
    name: "Cipitech Ltd."
    email: "cipitech.com@gmail.com"
    website: "www.cipitech.com"
  displayRequestDuration: true

app:
  delay-new-request-seconds: 60

  third-party:
    url: "http://api.exchangerate.host"
    rate-endpoint: "live"
    currency-endpoint: "list"
    access-key: "XXXXXXXXXXXXXXXXXX"  #Add your own access key here
    request-codes:
      key: "access_key"
      from: "source"
      to: "currencies"