offline:
  data-path: "C:/PUT_THE_PATH_OF_YOUR_CLONED_GIT_REPOSITORY_HERE/docker/offline_data"
  currencies-file: "${offline.data-path}/currencies.json"
  rates-folder: "${offline.data-path}/rates/"
  rates-file-suffix: ".json"