spring:
  profiles:
    active: third-party

  datasource:
    url: jdbc:postgresql://localhost:5434/exchange_rate
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      poolName: HikariPoolZZZ
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082
  servlet:
    context-path: /api

swagger:
  version: "1.0"
  title: "Exchange Rate REST API"
  description: "Documentation for the Exchange Rate demo application."
  contact:
    name: "Cipitech Ltd."
    email: "haris.tsipis@gmail.com"
    website: "www.cipitech.com"
  displayRequestDuration: true

app:
  delay-new-request-seconds: 60
  default-from-currency: "EUR"
  ignore-currencies: "SVC"