spring:
  profiles:
    active: dev, third-party
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      poolName: HikariPoolZZZ
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082
  servlet:
    context-path: /api

app:
  delay-new-request-seconds: 60

  third-party:
    url: "http://api.exchangerate.host"
    rate-endpoint: "live"
    currency-endpoint: "list"
    access-key: "XXXXXXXXXXXXXXXXXX"  #Add your own access key here
    request-codes:
      key: "access_key"
      from: "source"
      to: "currencies"