version: '2.4'

services:
  postgres_exchange_rate_converter:
    image: postgres:${POSTGRES_VERSION}
    networks:
      - exchange_rate_converter_net
    restart: always
    mem_limit: 2048m
    ports:
      - "5434:5432"
    logging:
      options:
        max-size: 100m
        max-file: "5"
    volumes:
      - postgres_exchange_rate_converter_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  exchange_rate_converter:
    build:
      context: ./
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url": "jdbc:postgresql://postgres_exchange_rate_converter:5432/${DATABASE_NAME}",
          "spring.datasource.username": "${DATABASE_USERNAME}",
          "spring.datasource.password": "${DATABASE_PASSWORD}",
          "spring.profiles.active": "${ACTIVE_PROFILES}",
          "third-party.access-key": "${ACCESS_KEY}",
          "offline.data-path": "${OFFLINE_DATA_FOLDER}"
        }'
    volumes:
      - exchange_rate_converter_data:${OFFLINE_DATA_FOLDER}
    ports:
      - "8082:8082"
    networks:
      - exchange_rate_converter_net
    restart: always
    mem_limit: 4096m
    depends_on:
      - postgres_exchange_rate_converter
    logging:
      options:
        max-size: 500m
        max-file: "10"

volumes:
  exchange_rate_converter_data:
    driver: local
  postgres_exchange_rate_converter_data:
    driver: local

networks:
  exchange_rate_converter_net:
    driver: bridge